### ISSUE TITLE
Export adress and private key to another wallet

### ISSUE THREAD

**Issue by dakleyer** [amjuarez/bytecoin#126]
Like some other people, I do not receive transactions on the offitial bytecoin wallet.

Is it posible to export our adress and private key to another  bytecoin wallet?

Will we see and be able to operate with the funds sended to our wallet?

Sorry, I know this is development Git but, to be honest, the actual code seems a PRE-BETA since is still not usable to collect coins.

**Comment by keylength** [comment]
As you seem to understand, this is not the place for your questions. Can you please close this and refer to this forum: https://bytecointalk.org/forumdisplay.php?fid=8 ~Thanks!
