### ISSUE TITLE
1.1.7.1 refuses to sync already synced wallet

### ISSUE THREAD

**Issue by dikdronk** [amjuarez/bytecoin#131]
Seriously guys, with 1/2 billion market cap, you should be able to maintain a simple wallet. Especially for a tech platform, the tech your investors rely on, should probably work.

I have rolled back to previous versions and still no luck.

Please fix this issue of the wallet refusing to sync with this latest release. Trying to keep the faith in your platform, but I might have to pull my investment if something simple like this is a hurdle you either refuse, or are not able to pass.

**Comment by keylength** [comment]
Can you please provide more details about your case? This is not a place for vapid complaints but rather a place to define specifics about software issues. Please either offer up enough details about your problem that this thread becomes useful or close. You can find a better home for this type of thread here: https://bytecointalk.org/forumdisplay.php?fid=8 . I understand your frustration, however it is important we remain disciplined in this particular forum so the developers can do their job.

For many, like me, the wallet works well. I agree that it seems fragile upon first setup. I have no idea what OS you are on, however on Windows, you have to have a decent swap file size and at least 25g free alongside that for the database to sync. Make sure you have plenty of room! It's super slow, for some reason I was limited to 8 peers but after 3-4 days of building, it's very stable and processes transactions in seconds on demand.

**Comment by dikdronk** [comment]
OSX 10.12.3, over 30GB free with a SYNCED (through June 7th, 2017) wallet version 1.1.7.1 (also in the title).

Note in the screenshot where the top block is different, and how the wallet thinks it is both synchronized, and not synchronized.

![image](https://user-images.githubusercontent.com/1664981/27367463-c4007254-5612-11e7-9b96-11e26f6addbb.png)

**Comment by cweigen** [comment]
@keylength I've been attempting to fully sync my wallet for weeks now. Sorry for butting in on this thread but when you first synced your wallet did you let it run for 3-4 days? I've tried installing this wallet on multiple different platforms all with sufficient free space and it takes maybe 3-4 hours to sync, but does not show any balance. Do I need to leave my computer on for a week or so with the wallet still reflecting that it's up to date for my balance to show?

**Comment by dikdronk** [comment]
@cweigen it took me around 4 days to sync the first time. Now I'm just in an endless loop with now balances showing up.

**Comment by cweigen** [comment]
@dikdronk with no* balances showing up?

**Comment by dikdronk** [comment]
It just shows my old cached balance behind the spinner.

![image](https://user-images.githubusercontent.com/1664981/27406187-c0c735fa-5699-11e7-82a1-aac63cfe008f.png)

**Comment by dikdronk** [comment]
@keylength I figured I would try the CLI wallet they have, and I'm getting an error/warning that says "Proof of work too weak for block...", does that shed light on anything?

**Comment by dikdronk** [comment]
Fixed the issue. Thanks for all the "help". Delete all your .sst files. Launch wallet, yes, erase and re-sync. Took 45 minutes.

**Comment by cweigen** [comment]
Sorry for lack of responses. I was not 100% sure which solutions might be helpful for your issue. Glad to hear you fixed it. I'm resyncing my wallet and on day 3 now, hoping for wallet to correctly reflect my balance.

**Comment by dikdronk** [comment]
Ha, thanks @cweigen  I'm a dickhead and that wasn't directed at you. Best of luck!
