### ISSUE TITLE
Wallet not syncing

### ISSUE THREAD

**Issue by Makgolli** [amjuarez/bytecoin#138]
Wallet version 1.1.7.1
OS Windows 10 pro 64 bit

Wallett Address:
26xTKwqXDMRLCfzoTiodK4Y6YtmPsWEYZd2aHMu46woWHo5XegpsTHjaq7BgTMzuFBUB7jykB1UYE67cbT2sua3J77SYX3m

Issue: Wallet show zero balance even though exchange confirms transaction
![nocoinerror](https://user-images.githubusercontent.com/28537377/27770673-ceab0544-5f3a-11e7-940e-e9833b83d808.jpg)

**Comment by keylength** [comment]
How many blocks are synced? Cannot see from your ss.

I currently have 1300533

**Comment by Makgolli** [comment]
Ok 1306448 blocks now.
You suspicion was right that the database was not synchronised. The footer menu is not visible at all unless the windows is fully maximised so I did not see that display at all The balance is updated after synchronisation

**Comment by abibell** [comment]
Yay. An issue has been closed 😊
