### ISSUE TITLE
Why using diffirent type of APIs?

### ISSUE THREAD

**Issue by lancehub** [amjuarez/bytecoin#31]
Some API are JSON based, some are HTTP, and some are 'BIN' API?
Why using diffirent type of APIs, especially it's hard to use BIN type APIs.

**Comment by pmitchev** [comment]
Can you paste the example here if it is ready?

**Comment by amjuarez** [comment]
I'm afraid we're currently behind our schedule on all non-core activities. I do believe we'll be able to provide you with the JS example in a couple of weeks.

**Comment by pmitchev** [comment]
Example how to use **get_o_tx.bin** in Python (request working, many notes on respond):
https://gist.github.com/pmitchev/fcee1345e20d70108e37

Example how to use **query_blocks.bin** in Python (request *almost* working) + notes:
https://gist.github.com/pmitchev/ec2934241761cbcdbcc3

I will be very happy for every contribution to it.

If you can fill the missing parts in my code or my notes I think it will be a lot easier for me and others to translate between different languages.

**Comment by lancehub** [comment]
that really helps, thank you!
