### ISSUE TITLE
osx 10.9 trying to build error Illegal instruction: 4

### ISSUE THREAD

**Issue by voluntaryistonly** [amjuarez/bytecoin#34]
Hi trying to build using binaries provide via: http://bytecoin.org/mac-download?binaries receiving error:
Illegal instruction: 4
have gcc installed, standard osx 10.9 install, any advice please...

**Comment by voluntaryistonly** [comment]
anything more on this? thanks...

**Comment by voluntaryistonly** [comment]
hello, anyone looking at this?

**Comment by amjuarez** [comment]
Please specify what Mac machine are you using exactly. Also, please clarify you message regarding building using binaries. Downloaded binaries are already compiled programs that you have to start with console.

**Comment by voluntaryistonly** [comment]
build using binaries provide via: http://bytecoin.org/mac-download?binaries  there are also build instructions there which i followed explicitly.  osx 10.9.5 mac mini 2009, Processor  2 GHz Intel Core 2 Duo, Memory  5 GB 1067 MHz DDR3, Graphics  NVIDIA GeForce 9400 256 MB

**Comment by voluntaryistonly** [comment]
i can pm you a crash report if you want...would rather not post here

**Comment by voluntaryistonly** [comment]
Hi, here is the error log report:

Process:         bytecoind [35290]
Path:            /Users/myusername/bytecoind
Identifier:      bytecoind
Version:         0
Code Type:       X86-64 (Native)
Parent Process:  sudo [35289]
Responsible:     Terminal [35053]
User ID:         0

Date/Time:       2015-02-25 16:59:16.245 +0000
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  B35D14B7-8D7E-A0F2-FA97-AFA5FE47F068

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000

Application Specific Information:
/Users/myusername/.bytecoin/bytecoind

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   bytecoind                     	0x000000010d0cd303 boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>() + 35
1   bytecoind                     	0x000000010d20d382 __cxx_global_var_init78 + 34
2   dyld                          	0x00007fff6ce39c2e ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 268
3   dyld                          	0x00007fff6ce39dba ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
4   dyld                          	0x00007fff6ce36a62 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 308
5   dyld                          	0x00007fff6ce368f6 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 54
6   dyld                          	0x00007fff6ce2a1da dyld::initializeMainExecutable() + 189
7   dyld                          	0x00007fff6ce2d560 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 2419
8   dyld                          	0x00007fff6ce2927b dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 477
9   dyld                          	0x00007fff6ce2905e _dyld_start + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x000000010d405fe0  rcx: 0x00007fff52b44c08  rdx: 0x00007fff52b44b80
  rdi: 0x000000010d405fd0  rsi: 0x00007fff52b44b70  rbp: 0x00007fff52b43cb0  rsp: 0x00007fff52b43c10
   r8: 0x00007fff6ce5c178   r9: 0x00007fff52b43c00  r10: 0x00aaff78aa525dab  r11: 0x00007fff75994d91
  r12: 0x000000010d3f9ba0  r13: 0x00007fff6ce5c0b0  r14: 0x000000010d405fd0  r15: 0x000000010d405fd0
  rip: 0x000000010d0cd303  rfl: 0x0000000000010206  cr2: 0x000000010d0cd2e0
  
Logical CPU:     1
Error Code:      0x00000000
Trap Number:     6

Binary Images:
       0x10d0bb000 -        0x10d3edfff +bytecoind (0) <568625A0-C211-3ABE-A65E-29A398EDD3EE> /Users/*/bytecoind
    0x7fff6ce28000 -     0x7fff6ce5b817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld
    0x7fff862ea000 -     0x7fff8633cfff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff8637f000 -     0x7fff86380ff7  libSystem.B.dylib (1197.1.1) <E303F2F8-A8CF-3DF3-84B3-F2D0EE41CCF6> /usr/lib/libSystem.B.dylib
    0x7fff86606000 -     0x7fff8660aff7  libcache.dylib (62) <BDC1E65B-72A1-3DA3-A57C-B23159CAAD0B> /usr/lib/system/libcache.dylib
    0x7fff86658000 -     0x7fff86659fff  libunc.dylib (28) <62682455-1862-36FE-8A04-7A6B91256438> /usr/lib/system/libunc.dylib
    0x7fff86804000 -     0x7fff8682bffb  libsystem_info.dylib (449.1.3) <7D41A156-D285-3849-A2C3-C04ADE797D98> /usr/lib/system/libsystem_info.dylib
    0x7fff8697e000 -     0x7fff86983fff  libmacho.dylib (845) <1D2910DF-C036-3A82-A3FD-44FF73B5FF9B> /usr/lib/system/libmacho.dylib
    0x7fff86cc9000 -     0x7fff86cf0ff7  libsystem_network.dylib (241.3) <8B1E1F1D-A5CC-3BAE-8B1E-ABC84337A364> /usr/lib/system/libsystem_network.dylib
    0x7fff86f14000 -     0x7fff86f43fd2  libsystem_m.dylib (3047.16) <B7F0E2E4-2777-33FC-A787-D6430B630D54> /usr/lib/system/libsystem_m.dylib
    0x7fff87e3f000 -     0x7fff87e46fff  libcompiler_rt.dylib (35) <4CD916B2-1B17-362A-B403-EF24A1DAC141> /usr/lib/system/libcompiler_rt.dylib
    0x7fff8837c000 -     0x7fff88405ff7  libsystem_c.dylib (997.90.3) <6FD3A400-4BB2-3B95-B90C-BE6E9D0D78FA> /usr/lib/system/libsystem_c.dylib
    0x7fff88440000 -     0x7fff88447ffb  libcopyfile.dylib (103.92.1) <CF29DFF6-0589-3590-834C-82E2316612E8> /usr/lib/system/libcopyfile.dylib
    0x7fff888b3000 -     0x7fff888d7fff  libxpc.dylib (300.90.2) <AB40CD57-F454-3FD4-B415-63B3C0D5C624> /usr/lib/system/libxpc.dylib
    0x7fff8946b000 -     0x7fff89494ff7  libc++abi.dylib (49.1) <21A807D3-6732-3455-B77F-743E9F916DF0> /usr/lib/libc++abi.dylib
    0x7fff89495000 -     0x7fff894a6ff7  libsystem_asl.dylib (217.1.4) <655FB343-52CF-3E2F-B14D-BEBF5AAEF94D> /usr/lib/system/libsystem_asl.dylib
    0x7fff8b2ed000 -     0x7fff8b2f4ff7  libsystem_pthread.dylib (53.1.4) <AB498556-B555-310E-9041-F67EC9E00E2C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff8ba9c000 -     0x7fff8baa2ff7  libsystem_platform.dylib (24.90.1) <3C3D3DA8-32B9-3243-98EC-D89B9A1670B3> /usr/lib/system/libsystem_platform.dylib
    0x7fff8bfd8000 -     0x7fff8bfd9ffb  libremovefile.dylib (33) <3543F917-928E-3DB2-A2F4-7AB73B4970EF> /usr/lib/system/libremovefile.dylib
    0x7fff8bfe9000 -     0x7fff8bfeafff  libsystem_sandbox.dylib (278.11.1) <0D0B13EA-6B7A-3AC8-BE60-B548543BEB77> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8c009000 -     0x7fff8c00bff3  libsystem_configuration.dylib (596.15) <4998CB6A-9D54-390A-9F57-5D1AC53C135C> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8c02f000 -     0x7fff8c037fff  libsystem_dnssd.dylib (522.92.1) <17B03FFD-92C5-3282-9981-EBB28B456207> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff8c44e000 -     0x7fff8c457ffb  libsystem_notify.dylib (121.20.1) <9B34B4FE-F5AD-3F09-A5F0-46AFF3571323> /usr/lib/system/libsystem_notify.dylib
    0x7fff8e7a6000 -     0x7fff8e7a9ff7  libdyld.dylib (239.4) <7C9EC3B7-DDE3-33FF-953F-4067C743951D> /usr/lib/system/libdyld.dylib
    0x7fff8e929000 -     0x7fff8e92dff7  libsystem_stats.dylib (93.90.3) <4E51D5B0-92A0-3D0D-B90E-495A1ED3E391> /usr/lib/system/libsystem_stats.dylib
    0x7fff8f614000 -     0x7fff8f615ff7  libsystem_blocks.dylib (63) <FB856CD1-2AEA-3907-8E9B-1E54B6827F82> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8f675000 -     0x7fff8f68ffff  libdispatch.dylib (339.92.1) <C4E4A18D-3C3B-3C9C-8709-A4270D998DE7> /usr/lib/system/libdispatch.dylib
    0x7fff8fbb5000 -     0x7fff8fd62f27  libobjc.A.dylib (551.1) <AD7FD984-271E-30F4-A361-6B20319EC73B> /usr/lib/libobjc.A.dylib
    0x7fff90079000 -     0x7fff9007bff7  libquarantine.dylib (71) <7A1A2BCB-C03D-3A25-BFA4-3E569B2D2C38> /usr/lib/system/libquarantine.dylib
    0x7fff9038b000 -     0x7fff90390ff7  libunwind.dylib (35.3) <78DCC358-2FC1-302E-B395-0155B47CB547> /usr/lib/system/libunwind.dylib
    0x7fff90391000 -     0x7fff903dffff  libcorecrypto.dylib (161.1) <F3973C28-14B6-3006-BB2B-00DD7F09ABC7> /usr/lib/system/libcorecrypto.dylib
    0x7fff9046b000 -     0x7fff9046cff7  libDiagnosticMessagesClient.dylib (100) <4CDB0F7B-C0AF-3424-BC39-495696F0DB1E> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff90bec000 -     0x7fff90bf6fff  libcommonCrypto.dylib (60049) <8C4F0CA0-389C-3EDC-B155-E62DD2187E1D> /usr/lib/system/libcommonCrypto.dylib
    0x7fff90c32000 -     0x7fff90c4eff7  libsystem_kernel.dylib (2422.115.4) <9EDE872E-2A9E-3A78-8E1D-AB790794A098> /usr/lib/system/libsystem_kernel.dylib
    0x7fff90f5b000 -     0x7fff90f62ff8  liblaunch.dylib (842.92.1) <A40A0C7B-3216-39B4-8AE0-B5D3BAF1DA8A> /usr/lib/system/liblaunch.dylib
    0x7fff90f63000 -     0x7fff90f7eff7  libsystem_malloc.dylib (23.10.1) <A695B4E4-38E9-332E-A772-29D31E3F1385> /usr/lib/system/libsystem_malloc.dylib
    0x7fff92631000 -     0x7fff92673ff7  libauto.dylib (185.5) <F45C36E8-B606-3886-B5B1-B6745E757CA8> /usr/lib/libauto.dylib
    0x7fff92b16000 -     0x7fff92b16ff7  libkeymgr.dylib (28) <3AA8D85D-CF00-3BD3-A5A0-E28E1A32A6D8> /usr/lib/system/libkeymgr.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 3210
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=72.7M resident=38.1M(52%) swapped_out_or_unallocated=34.6M(48%)
Writable regions: Total=17.6M written=196K(1%) resident=256K(1%) swapped_out=0K(0%) unallocated=17.3M(99%)
 
REGION TYPE                      VIRTUAL
===========                      =======
Kernel Alloc Once                     4K
MALLOC                             9396K
MALLOC (admin)                       16K
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                           8K
__DATA                              752K
__LINKEDIT                         64.5M
__TEXT                             8364K
shared memory                         4K
===========                      =======
TOTAL                             146.6M

**Comment by amjuarez** [comment]
There is a big chance that our current version won't work on Inter Core 2 Duo due to the difference in supported processor instructions.
 Also, you don't have to compile precompiled binaries.

**Comment by voluntaryistonly** [comment]
I trust that the next version will be able to do that?thanks ;-)
