### ISSUE TITLE
On a bytecoin fork, seed nodes cannot be connected to

### ISSUE THREAD

**Issue by xpbcreator** [amjuarez/bytecoin#35]
Hi Monero devs,

I'm the creator of [Pebblecoin](https://bitcointalk.org/index.php?topic=909624.0).  I have an issue with the hardcoded seed nodes and I was wondering if you have had any similar issues or could help point me to a fix.  As it is now, the 5 seed nodes cannot be connected to.  From the client side, I get timeouts: 

    COMMAND_HANDSHAKE invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)

I tried upping the timeout to 60 seconds yet it still times out.  From the seed node side, I get these potentially relevant error messages:

    [sock 32] Some problems at write: Broken pipe:32

and

    [P2P7]Failed to get remote endpoint: Transport endpoint is not connected:107
    [P2P7]ERROR ../../contrib/epee/include/net/abstract_tcp_server2.inl:638 [sock 54] Failed to start connection, connections_count = 61

and

    [P2P5]Failed to invoke command 1002 return code -3
    [P2P5][69.60.113.27:52699 INC]COMMAND_TIMED_SYNC invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)

Any idea what may be causing the issues?  I ask because I didn't change the networking code.  I added a new type of command, but that only comes in after the handshake process is done already.  The issue happens on any node that has more than a few connections to it.

Thanks,
xpbcreator

**Comment by amjuarez** [comment]
We're Bytecoin devs :)
Did you manage to solve the issue?
