### ISSUE TITLE
simple wallet 1.0.3 misses command "refresh"

### ISSUE THREAD

**Issue by shszwb** [amjuarez/bytecoin#39]
Unlike old version, simple wallet 1.0.3(source or built) does not have command "refresh" in the command list, while in the user guide "refresh" is valid.

**Comment by amjuarez** [comment]
Starting with version 1.0.3 simplewallet doesn't require refresh command as it is synced with the daemon automatically. This is allowed with IWallet implemented in new simplewallet. 

It seems that the user guide has not been updated yet. Thank you.

**Comment by amjuarez** [comment]
All manuals have been updated.
