### ISSUE TITLE
Simplewallet makes no .keys files

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#40]
Simplewallet does not make .keys file for newly generated wallets. I have this issue on both my Mac and Ubuntu VPS.
I have even tried on blank Ubuntu 14.04 VPS with the same result.

**Comment by amjuarez** [comment]
It does make the wallet file, but without any extension. If you call your wallet file "filename", this is exactly what it's going to be called in your system. I think we're going to fix it this week.

**Comment by amjuarez** [comment]
With the latest fix simplewallet creates .wallet files (same format as for Bytecoin GUI Wallet).

**Comment by pmitchev** [comment]
To discribe my problem better I will paste 'ls -l' after I import an old wallet:
```
-rw-r--r--  1 pmitchev  staff       289 Feb  3 02:22 pool.keys.back
-rw-r--r--  1 pmitchev  staff  90287624 Apr 16 23:17 pool.wallet
```
I have to use 90mb to backup a single wallet? `pool.wallet` is the only file `simplewallet` creates on my system.

**Comment by amjuarez** [comment]
Both Bytecoin Wallet and simplewallet use the same file structure. In case you wish to make a backup in Bytecoin Wallet, there's a "Backup wallet" option in the menu. It creates the .wallet file with the keys only. 
We're currently implementing the same backup function for simplewallet, which is not currently available.

Is it a suitable use case for you?

**Comment by pmitchev** [comment]
Unfortunately, no. But your answer make the things a lot more clear for me :)
