### ISSUE TITLE
reset in simplewallet creates "Segmentation fault" 

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#42]
When I try to use 'reset' command in simplewallet on Ubuntu 14.04 I got this as result:
```
[wallet 21fJAC]: reset
Reset is complete successfully
[wallet 21fJAC]: Segmentation fault
$ 
```
The machine is a fresh Vultr VPS.

**Comment by amjuarez** [comment]
Hello, 
Please provide more information regarding the issue. Here is an instruction that will help you do that: 

1. Compile the wallet in debug mode
2. Follow these commands: 

$mkdir -p /tmp/cores
$sudo su
#echo "/tmp/cores/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern
#exit
$ulimit -c unlimited

3. Start the wallet and make it crash to create a core dump.  
4. Go to /tmp/cores, last core dump will be the file that starts with “core.” and with a latest creation date. 
5. Archive it alongside with simplewallet and upload it to any file hosting. 
6. Send us the link to it. 

Thank you.

**Comment by pmitchev** [comment]
Sorry for the delayed reply. I cannot provide the info you requested, but the problem is easy to reproduce. It occurs on every machine with <1GB RAM I tested. Tested on 512MB digital ocean and 768MB vultr. I know the recommendation is 2gb ram, but I didn't have this problem the previews version

**Comment by amjuarez** [comment]
Thank you for detailed report. 

We will try to reproduce this bug on similar hardware and will get back to you with an answer.

**Comment by amjuarez** [comment]
Hello,
In 1.0.4 release we've fixed significant amount of bugs. Please let us know if you still can reproduce this problem.
