### ISSUE TITLE
Duplicated work

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#44]
I see a lot of duplicated work in net_node.cpp and NetNodeConfig.cpp. Which one is planed for longterm support?

**Comment by amjuarez** [comment]
Hello, 

We are currently on a stage of active code refactoring and we still suffer some duplication of the code. 

In this particular case, NetNodeConfig.cpp is planned for longterm support. We will get rid of all such cases in nearest future.

**Comment by andre-amorim** [comment]
Hi, amjuarez,

I'm just trying to visualise
<https://wiki.bytecoin.org/images/b/be/Bytecoin_API_scheme.png> and get the
whole picture, NetNodeConfig.cpp is for *INode* and *INodeObserver*
interfaces isn't it?

Thanks,
All the best,
--aa

**Comment by amjuarez** [comment]
Hello Andre, 

Both INode and INodeObserver are public API interfaces that everyone can use to work with Bytecoin network. 
NetNodeConfig.cpp is a part of the Bytecoin P2P network implementation and does not correspond with API interfaces. 

Please don’t hesitate to contact us in case you have more questions or suggestions.
