### ISSUE TITLE
minedMoneyUnlockWindow not working?

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#45]
I am able to send transaction via simplewallet right after I receive them (0 blocks confirmed). I always see "locked amount" as 0. Is CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW only apply for mined blocks, or for all transfers?

**Comment by pmitchev** [comment]
I see the transaction was also included in the blockchain. (7 blocks since the initial transfer)

**Comment by amjuarez** [comment]
Hello, 

CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW only applies to mined blocks, not all transfers. 

As you stated correctly you are able to send usual transfers right away but to spend mined coins you should wait 10 confirmations. (blocks)
