### ISSUE TITLE
Logfiles full of "The stream is ended"

### ISSUE THREAD

**Issue by wallet42** [amjuarez/bytecoin#46]
We query the daemon and wallet via /json_rpc interface, the correct results are given but the logs of daemon and wallet are full of 
````
WARNING Connection error: The stream is ended
````

The related lines maybe somewhere here:
https://github.com/amjuarez/bytecoin/blob/master/src/HTTP/HttpParser.cpp#L216

After the body was read, the stream is always EOF, unless keep-alive is used. This is not an error and should not create a log message.

PS: Also a better error message in the real case should go like  "Connection error: Stream ended unexpectedly" and include origin host and port for easier identification and debugging.

**Comment by amjuarez** [comment]
Hello and thank you for your feedback. 
We are aware of this issue and we are doing our best to resolve it. We are currently trying to find the best solution for the issue. 
We will update this issue when there is progress.

**Comment by amjuarez** [comment]
The issue has been resolved in Bytecoin 1.0.6, which was released today.
