### ISSUE TITLE
RpcNodeConfiguration bug

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#47]
When i try to use daemon-address and daemon-port options on walletd with a config file, they return the default values.
(daemonHost = "127.0.0.1";
  daemonPort = 8081;)

**Comment by amjuarez** [comment]
There is indeed an issue with config file values. It is going to be fixed in the next update. As for now we recommend you using command line arguments.

**Comment by amjuarez** [comment]
Issue has been fixed.
