### ISSUE TITLE
COMMAND_HANDSHAKE Failed, wrong network!

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#48]
I am trying to create a simple dummy network using version 1.0.4 only.
I am starting a seed node on Linux (v1.0.4)
When I try to connect on Windows I am getting this error and it never connects to the seed node:
```
02:26:09.454001 ERROR [162.243.247.45:28080 OUT] COMMAND_HANDSHAKE Failed, wrong network!  (7538a4b2-49b9-c5c4-da5e-4a2972e71673),closing connection.
02:26:09.460126 WARNING Failed to HANDSHAKE with peer 162.243.247.45:28080
```
The problem does not exists on Mac and Linux

**Comment by amjuarez** [comment]
We have tried to reproduce this issue, but everything is working with Bytecoin original source code. Could you provide more information on the issue?

**Comment by andre-amorim** [comment]
In Java-hotspot Urs?

**Comment by pmitchev** [comment]
I use the code from this repository:
https://github.com/pmitchev/testcoin
Linux and Windows binaries:
https://www.dropbox.com/s/p0z9tfzyglqu648/testcoind.zip?dl=0
https://www.dropbox.com/s/pookzeomyuo9t8s/testcoind.exe.zip?dl=0
I am building the Windows binaries with boost 1.58 instead of 1.55, because of Visual Studio 2013. I also tried 1.57 with the same result. Here is an exact list of what is installed on the Windows machine (VPS on Azure. Windows Server 2012 R2):
https://github.com/forknote/cryptonote-generator/blob/master/docs/windows-requirements-install.md
On the Linux machine I am using boost 1.55

**Comment by amjuarez** [comment]
Can you provide a step-by-step overview of how you are creating a fork? We need that to identify potential issues.
What's more, are you able to reproduce this problem with Bytecoin source code? Our experiments do not prove that the issue is present with original Bytecoin code.

**Comment by pmitchev** [comment]
1. I make those changes in the original code:
https://github.com/pmitchev/testcoin/commit/bde47c6b7c575ab04aee43cc372ff1ebd3306d7a
2. I buy blank Ubuntu 14.04 VPS (2 GB RAM) (32GB on compile time)
3. I install dependencies:
```
wget https://raw.githubusercontent.com/forknote/cryptonote-generator/master/configure.sh
```
bash configure.sh
4. Clone and compile:
```
git clone https://github.com/pmitchev/testcoin/
cd testcoin
mkdir -p build/release; cd build/release
cmake -D STATIC=ON -D ARCH="x86-64" -D CMAKE_BUILD_TYPE=Release ../..
make -j
```
5. Run the daemon and start generating blocks:
```
cd src
./testcoind
start_mining 21YR5mw5BF2ah3yVE3kbhkjDwvuv21VR6D7hnpm4zHveDsvq5WEwyTxXLXNwtU5K4Pen89ZZzJ81fB3vxHABEUJCAhxXz2v
```
6. I get VPS from Azure. Team Foundation Server 2013 Update 4 image. A2 size
7. I install dependencies:
https://github.com/forknote/cryptonote-generator/blob/master/docs/windows-requirements-install.md
8. Download and build:
```
git clone https://github.com/pmitchev/testcoin/
cd testcoin
mkdir build
cd build
cmake -G "Visual Studio 12 Win64" ".."
msbuild.exe Bytecoin.sln /p:Configuration=Release
```
9. Run the daemon:
```
cd src\Release
testcoind.exe
```

**Comment by pmitchev** [comment]
I cannot reproduce the problem on the Bytecoin network. I can only produce it when all seed nodes are with version 1.0.4

**Comment by amjuarez** [comment]
We have just followed all steps you've mentioned. We've used your testcoin repo and followed each step precisely. We even mined some blocks to the very same address. The only difference is that we didn't purchase Windows VPS from Azure but used one of our remote machines instead.

However, we could not reproduce the issue. The Windows daemon connects to the seed easily. This leads us to believe that you might have errors in the sources. Could you check whether network identifiers and seed nodes are correct and the same on both machines?

One more thing that might help us hunt the issue is the daemon log of the Linux machine. Please, set it to log level 4 (set_log 4) and try connecting with Windows machine.

**Comment by amjuarez** [comment]
One more issue I'd like to mention. There is no need to start mining on seed nodes. The daemon that connects to a seed node does not synchronize blockchain with it, but takes the peer list only.

**Comment by pmitchev** [comment]
This is super odd. Every coin I am building on this machine has the issue. And everyone using those binaries have the issue:
https://bitcointalk.org/index.php?topic=1086075.0;topicseen
I will try to build on another machine and if I still have it I will send the log. Sorry for the lost time.

**Comment by pmitchev** [comment]
The problem was with the default settings of the Windows firewall. Setting the log level to 4 helped me debug.
