### ISSUE TITLE
simplewallet heigh print bug (probably)

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#51]
I saw this print in simplewallet on one of my transfers:
```
Height 267413, transaction af06ab60a7f4471e65b7a2b2e48546ceae21bd17f17acd2f878a64eb01d796ab, received 1000.00000000
Height 18446744073709551615, transaction 49517c7edfba3ef86ef373fd6f2e02730f4e2f1f492eeac2940af0e44f33eea1, received 1000.00000000
```
I didn't manage to reproduce it. The wallet was new. The transaction had payment_id. I see the height correctly in list_transfers. All the other transactions' height are printed correctly. Wallet version 1.0.5. It's on the Dashcoin network

**Comment by pmitchev** [comment]
I just realised those are unconfirmed transactions. (I used 2 simplewallets with 1 daemon). Not a bug, but it's confusing

**Comment by amjuarez** [comment]
Thank you for reporting.  

We will definitely fix it. We will update an issue what it is done.

**Comment by amjuarez** [comment]
Today's Bytecoin 1.0.6 release fixes the issue. The example you've provided would be printed as follows
```
Height 267413, transaction af06ab60a7f4471e65b7a2b2e48546ceae21bd17f17acd2f878a64eb01d796ab, received 1000.00000000
Unconfirmed transaction 49517c7edfba3ef86ef373fd6f2e02730f4e2f1f492eeac2940af0e44f33eea1, received 1000.00000000
```
