### ISSUE TITLE
Blockchain file removed

### ISSUE THREAD

**Issue by nurazhar** [amjuarez/bytecoin#80]
https://mega.nz/#!NUxk0YTJ!9Mv1kj0GtOw542kLLCaCXLuZWmc5AUNNtvm0j52TBpM

where to download?

**Comment by andre-amorim** [comment]
who knows ???

ps-> ... well I have a bytecoin blockchian.bin saved not that long ago ...
but it is stored in a off in a ssd drive, I need to attach it to some bus
then upload to a reachable network address  ...
